name: Deploy to GitHub Pages

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and Deploy
      uses: edwardtufte/et-gh-pages@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
