
name: Deploy to GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build and deploy
      run: |
        npm install
        npm run build
        gh-pages -d build
    - name: Commit and push
      run: |
        git add .
        git commit -m "Deploy"
        git push origin HEAD:main
